services:
  bot:
    image:
      tg-housing-service:bot
    build:
      context: .
    env_file:
      - .env
    environment:
      - APP_SERVICE=bot
    volumes:
      - ${PWD}/.data:/app/.data

  test:
    image:
      tg-housing-service:test
    build:
      context: .
      args:
        DEV_DEPS: "true"
    env_file:
      - .env
    environment:
      - APP_SERVICE=test
    volumes:
      - ${PWD}/.data:/app/.data
