- hosts: all
  gather_facts: no
#  remote_user: "{{ ssh_user }}"
  vars:
    ansible_python_interpreter: /usr/bin/python

  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - debug:
        var: ansible_facts

    - name: Unzip etc remote artefact
      ansible.builtin.unarchive:
        src: "{{ artefact_url }}"
        dest: "{{ project_root }}"
        remote_src: yes

    - name: Run deploy script
      shell: "bash {{ project_root }}/bin/deploy"
