- hosts: all
  become: yes
  remote_user: "{{ user }}"
  tasks:
    - name: Unzip etc remote artefact
      ansible.builtin.unarchive:
        src: "{{ artefact_url }}"
        dest: "{{ project_root }}"
        remote_src: yes

    - name: Run deploy script
      shell: "bash {{ project_root }}/bin/deploy"
