- hosts: all
  gather_facts: no
  remote_user: "{{ ssh_user }}"
  vars:
    ansible_python_interpreter: /usr/bin/python

  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - debug:
        var: ansible_facts

    - name: Backup script exists
      stat:
        path: "{{ project_root }}/bin/backup"
      register: bin_backup_register

    - name: Run backup
      shell: "bash {{ project_root }}/bin/backup"
      when:
        bin_backup_register.stat.exists:

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /srv/myfiles/foo.conf
        dest: "{{ project_root }}/tg-housing-artefact.tar.gz"
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: "0644"

    - name: Unzip artefact
      ansible.builtin.unarchive:
        src: "{{ project_root }}/tg-housing-artefact.tar.gz"
        dest: "{{ project_root }}"
        remote_src: no

    - name: Run deploy
      shell: "bash {{ project_root }}/bin/deploy"
