#!/bin/sh


if [ "${APP_SERVICE}" = "bot" ]
  then
    /bin/bash docker-crontab
    python -m src.main

elif [ "${APP_SERVICE}" = "test" ]
  then
    export COVERAGE_FILE=/tmp/.coverage
    export RUFF_CACHE_DIR=/tmp/.ruff
    ruff check && \
    coverage run -m pytest -o cache_dir=/tmp && \
    coverage report

elif [ "${APP_SERVICE}" = "check-all" ]
  then
    python -m src.cli.check_all

else
  echo "APP_SERVICE environment variable is unexpected or was not provided (APP_SERVICE='${APP_SERVICE}')" >&2
  kill -s SIGINT 1

fi
