#!/bin/bash
set -e

export CRONTAB_APP_SERVICE="check-all"
export CRONTAB_LOGFILE="/app/.data/cron.log"

echo "=========="
echo "Start preparing and run cron job service"
echo "=========="
echo ""
echo "Exporting variables to ${CRONTAB_ENVFILE}..."
declare -p | grep -Ev 'BASHOPTS|BASH_VERSINFO|EUID|PPID|SHELLOPTS|UID' >> "${CRONTAB_ENVFILE}" && \
echo "APP_SERVICE=check-all" >> "${CRONTAB_ENVFILE}" && \
echo "PYTHONPATH=/app" >> "${CRONTAB_ENVFILE}" && \
echo "  detected cron record: ${CRONTAB_RECORD}"
echo "  formed file: ${CRONTAB_ENVFILE}"
echo "  log file: ${CRONTAB_LOGFILE}"
echo ""
service cron start
echo "  cron started..."

echo ""
echo "=========="
echo ""
