name: Deploy
on:
  push:
    branches:
      - 'main'
      - 'tech/12-deploy'
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#
#      - name: Prepare .env file
#        env:
#          PWD: $(PWD)
#        run: |
#          cp .env.template .env
#          env >> .env
#
#      - name: Build image
#        run: docker compose build test
#
#      - name: Run tests
#        run: docker compose up --exit-code-from test test

  build:
#    needs: [test]
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Log in to the Container registry
#        uses: docker/login-action@v3
#        with:
#          registry: ${{ env.REGISTRY }}
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=ref,event=tag,value=latest

#      - name: Build and push Docker image
#        id: push
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Creating artifacts
        if: success()
        id: artefacts
        uses: actions/upload-artifact@v4
        with:
          name: deploy-artefacts
          path: |
            etc
            !etc/ansible/*
          retention-days: 7

      - name: Debug
        run: |
          echo ${{ steps.artefacts.outputs.artifact-url }}
          echo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          echo ${{needs.build.outputs.image_tag}}
          echo ${{ github.workspace }}

      - name: Prepare inventory file
        run: |
          mkdir ~/.ssh
          echo "[all]" > ${{ github.workspace }}/inventory.ini
          echo "${{ secrets.PROD_SSH_HOST }}" >> ${{ github.workspace }}/inventory.ini
          echo "${{ secrets.SSH_PKEY }}" > ${{ github.workspace }}/inventory.ini
          cat ${{ github.workspace }}/inventory.ini

      - name: Run deploy
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ${{ github.workspace }}/etc/ansible/deploy.yaml
          key: ${{secrets.SSH_PKEY}}
#          inventory: |
#            [all]
#            ${{ secrets.PROD_SSH_HOST }}
#          known_hosts: |
#            ${{ secrets.PROD_SSH_HOST }} ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
          options: |
            --extra-vars "artefact_url=${{ steps.artefacts.outputs.artifact-url }} project_root=${{ secrets.PROD_PROJECT_ROOT }} image_tag=${{needs.build.outputs.image_tag}}"                     
            --verbose
          configuration: |
            [defaults]
            host_key_checking = False
