name: Deploy
on:
  push:
    branches:
      - 'main'
      - 'tech/12-deploy'
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ARTEFACT_NAME: tg-housing-artefact.tar.gz

jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#
#      - name: Prepare .env file
#        env:
#          PWD: $(PWD)
#        run: |
#          cp .env.template .env
#          env >> .env
#
#      - name: Build image
#        run: docker compose build test
#
#      - name: Run tests
#        run: docker compose up --exit-code-from test test

  build:
#    needs: [test]
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Log in to the Container registry
#        uses: docker/login-action@v3
#        with:
#          registry: ${{ env.REGISTRY }}
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=ref,event=tag,value=latest

#      - name: Build and push Docker image
#        id: push
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create artefact
        run: |
          cp .env.template etc/env.template
          cd etc
          tar -czf ${{ github.workspace }}/${{ env.ARTEFACT_NAME }} *

      - name: Debug
        run: |
          echo ${{ steps.artefacts.outputs.artifact-url }}
          echo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          echo ${{needs.build.outputs.image_tag}}
          echo ${{ github.workspace }}
          ls -lah ${{ github.workspace }}/${{ env.ARTEFACT_NAME }}

      - name: Prepare inventory file
        run: |
          echo "[all]" > ${{ github.workspace }}/etc/ansible/.hosts
          echo "${{ secrets.SSH_HOST }} ansible_port=${{ secrets.SSH_PORT }}" >> ${{ github.workspace }}/etc/ansible/.hosts

      - name: Prepare SSH file
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PKEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - name: Delivery Updates
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: delivery.yaml
          directory: ${{ github.workspace }}/etc/ansible/
          options: |
            --extra-vars "artefact_path=${{ github.workspace }}/${{ env.ARTEFACT_NAME }} project_root=${{ secrets.PROD_PROJECT_ROOT }} registry_url=${{ env.REGISTRY }} ssh_user=${{ secrets.SSH_USER }}"                     
            --verbose
            --inventory .hosts
          configuration: |
            [defaults]
            host_key_checking = False
            ssh_args = -o StrictHostKeyChecking=False

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PKEY }}
          script: |
            export DEPLOY_MODE=CI
            export DOCKER_IMAGE_URL=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            export DOCKER_IMAGE_TAG=${{needs.build.outputs.image_tag}}
            cd ${{ secrets.PROD_PROJECT_ROOT }}
            sh bin/deploy
