name: Test
on:
  push:
    branches:
      - feature/6-prepare-for-deploy

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build image
        run: docker-compose build test

      - name: Run tests
        run: docker-compose up --exit-code-from test test
